### ISSUE TITLE
Авторизация по ключам

### ISSUE THREAD

**Issue by zCirill** [vasilevkirill/pupirka#1]
Прошу рассмотреть возможность добавления фичи - аутенфикация по ключам

**Comment by vasilevkirill** [comment]
Необходимо сделать глобальный ключ и уникальный для каждого устройства?

**Comment by zCirill** [comment]
На мой взгляд глобальный ключ (и учётку по умолчанию) имеет смысл вынести в
отдельный файл, в котором можно описать дефолтовые значения.
Так же было бы удобно переопределять дефолтовые значения для конкретных
устройств

Представим себе, что у нас 10 устройств.

8 из них имеют учётку bckp и используют ключ по пути some/path/bckp.rsa

А два устройства
Учетку dump и admon с другими ключами.

Соответственно для подключения к 8 устройствам, подставляются глобальные
значения, для 2 других описываем локальные

ср, 2 сент. 2020 г., 20:20 Kirill <notifications@github.com>:

**Comment by vasilevkirill** [comment]
added
